name: Build Image

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Create NuGet token file
        run: echo "${{ secrets.NUGET_TOKEN }}" > nuget_token.txt

      - name: Build and Push Docker Image for Cypherly.SagaOrchestrator.API
        run: |
          docker buildx build --platform linux/amd64 \
            --secret id=nuget_token,src=nuget_token.txt \
            -t ${{ secrets.DOCKER_USERNAME }}/dev-cypherly-saga-machine:latest \
            -f SagaOrchestrator.API/Dockerfile . \
            --push
